rvm: 2.5.1
before_script: "cd public/images/icons/; tar xfz icons.tgz; mysql -e 'create database sinforum_test;'; cd ../../../"
script: "time bundle exec rspec spec"
bundler_args: --without development
